---
title: "Aedes paper images"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.pos = 'H', fig.align = "center",
  message = FALSE, warning = FALSE
)
```


```{r Load libraries}
library(here)
library(tidyverse)
library(viridis)
#library(extrafont)

#loadfonts(device = "win")
#windowsFonts(Times = windowsFont("TT Times New Roman"))
```


```{r Prep data}
main_fit_df <- read.csv(here("output", "main_fit_df.csv")) %>% 
  mutate(Model = "Main") %>% 
  select(-X)
larval_fit_df <- read.csv(here("output", "fit_with_container_index_df.csv")) %>% 
  mutate(Model = "Larval")
adult_fit_df <- read.csv(here("output", "fit_full_w_adult_no_pred.csv")) %>% 
  mutate(Model = "Adult")


display_names_vec <- c(
  "Sex [ref: Female]",
  "     Male", 
  "Age", 
  "Insecticide used [ref: No]",
  "     Yes",
  "Larvicide used [ref: No]",
  "     Yes ",
  "Number of toilets",
  "Number of water containers",
  "Modal land type [ref: Urban]",
  "     Rice paddy",
  "     Cropland",
  "Distance to river (std.)", 
  "Wet season [ref: No]",
  "     Yes  ",
  "Flooding index (NFI)",
  "Larval container index",
  "Ave. trapped mosquitos"
) 

pred_names_vec <- c(
  "Sex [ref: Female]",
  "Male", 
  "Age", 
  "Insecticide used [ref: No]",
  "Insecticide used",
  "Larvicide used [ref: No]",
  "Larvicide used",
  "Number of toilets",
  "Number of water containers",
  "Modal land type [ref: Urban]",
  "Rice paddy",
  "Cropland",
  "Distance to river (std.)", 
  "Wet season [ref: No]",
  "Wet season",
  "Flooding index (NFI)",
  "Container index",
  "Ave. trapped mosquitos"
  )


all_results <- main_fit_df %>% 
  bind_rows(larval_fit_df) %>% 
  bind_rows(adult_fit_df) %>% 
  filter(pred_names != "(Intercept)") %>% 
  add_row(pred_names = "Rice paddy", Model = "Adult") %>% 
  add_row(pred_names = "Wet season", Model = "Adult") %>%
  add_row(pred_names = "Container index", Model = "Main") %>% 
  add_row(pred_names = "Container index", Model = "Adult") %>%
  add_row(pred_names = "Ave. trapped mosquitos", Model = "Main") %>%
  add_row(pred_names = "Ave. trapped mosquitos", Model = "Larval") %>%
  add_row(pred_names = "Sex [ref: Female]", Model = "Main") %>% # Sex [ref: Female]
  add_row(pred_names = "Sex [ref: Female]", Model = "Larval") %>% 
  add_row(pred_names = "Sex [ref: Female]", Model = "Adult") %>% 
  add_row(pred_names = "Insecticide used [ref: No]", Model = "Main") %>% # Insecticide used [ref: No]
  add_row(pred_names = "Insecticide used [ref: No]", Model = "Larval") %>% 
  add_row(pred_names = "Insecticide used [ref: No]", Model = "Adult") %>% 
  add_row(pred_names = "Larvicide used [ref: No]", Model = "Main") %>% # Larvicide used [ref: No]
  add_row(pred_names = "Larvicide used [ref: No]", Model = "Larval") %>% 
  add_row(pred_names = "Larvicide used [ref: No]", Model = "Adult") %>% 
  add_row(pred_names = "Modal land type [ref: Urban]", Model = "Main") %>% # Modal land type [ref: Urban]
  add_row(pred_names = "Modal land type [ref: Urban]", Model = "Larval") %>% 
  add_row(pred_names = "Modal land type [ref: Urban]", Model = "Adult") %>% 
  add_row(pred_names = "Wet season [ref: No]", Model = "Main") %>% # Wet season [ref: No]
  add_row(pred_names = "Wet season [ref: No]", Model = "Larval") %>% 
  add_row(pred_names = "Wet season [ref: No]", Model = "Adult") %>% 
  mutate(display_names = factor(
    pred_names, 
    levels = rev(pred_names_vec), 
    labels = rev(display_names_vec) 
  )) %>% 
  mutate(Model = factor(Model, levels = c("Main", "Larval", "Adult"))) %>% 
  arrange(display_names)
```


```{r Plot parameters}
alpha <- 0.8

dodge <- 0.8

min_val <- min(
  all_results$quant025[all_results$display_names != "Flooding index (NFI)"],
  na.rm = TRUE
)
max_val <- max(
  max(
    all_results$quant975[all_results$display_names != "Flooding index (NFI)"],
    na.rm = TRUE
  ),
  0.6
)
```


```{r Produce 1 plot}
all_results %>% 
  ggplot(aes(x = mean, y = display_names, color = Model)) +
    geom_point(
      alpha = alpha, 
      position = position_dodge2(width = dodge, reverse = TRUE)
    ) +
    geom_linerange(
      aes(xmin = quant025, xmax = quant975), 
      alpha = alpha, 
      position = position_dodge2(width = dodge, reverse = TRUE)
    ) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    theme_bw(base_size = 12) +
    theme(
      panel.border = element_blank(),
      axis.text.y = element_text(hjust = 0),
      axis.ticks.y = element_blank(),
      axis.text.x=element_text(),
      panel.grid.major = element_line(colour = "gray90"),
      axis.ticks.length=unit(.25, "cm")
    ) +
    xlab("Effect size") +
    ylab("Covariate") +
  scale_color_manual(values = c("#440154FF", "#31688EFF", "#35B779FF")) +
  #scale_color_manual(values = c("#3F3994FF", "#7A0403FF", "#2DB17EFF")) +
  coord_cartesian(xlim=c(min_val, max_val))
```

