---
output: 
  pdf_document:
    keep_tex:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.pos = 'H', fig.align = "center",
  message = FALSE, warning = FALSE
)
```


```{r load libraries}
library(knitr)
library(kableExtra)
library(here)
library(tidyverse)
```


```{r Load in estimate results}
main_results_table <- read_csv(
  here("output", "main-model-results-table.csv"),
  show_col_types = FALSE
) %>% 
  select(-c("...1"))
```


```{r Table 1 Summary stats}
options(knitr.kable.NA = '')

main_results_table %>% 
  select(-c(variable1, Estimate)) %>% 
kbl(
  #booktabs = TRUE, 
  col.names = c(" ", "Visit 1", "Visit 2", "Visit 3", "Visit 4")
) %>% 
  kable_styling() %>% 
  pack_rows(
    index = c(
      "Gender" = 2,
      " " = 1,
      "Land type" = 3,
      " " = 1,
      "Insecticide" = 2,
      "Larvicide" = 2,
      " " = 2,
      "Wet season" = 2,
      " " = 1
    ), 
    bold = FALSE
  )
```

\newpage

```{r Table 2 data prep}
main_fit_df <- read_csv(
  here("output", "main_fit_df.csv"),
  show_col_types = FALSE
) %>% 
  mutate(Main = paste0(
    round(mean, 3), " (", round(quant025, 3), ", ", round(quant975, 3), ")"
  )) %>% 
    select(pred_names, Main) 

larval_fit_df <- read_csv(
  here("output", "fit_with_container_index_df.csv"),
  show_col_types = FALSE
) %>% 
  mutate(Larval = paste0(
    round(mean, 3), " (", round(quant025, 3), ", ", round(quant975, 3), ")"
  )) %>% 
    select(pred_names, Larval) 

adult_fit_df <- read_csv(
  here("output", "fit_full_w_adult_no_pred.csv"),
  show_col_types = FALSE
) %>% 
  mutate(Adult = paste0(
    round(mean, 3), " (", round(quant025, 3), ", ", round(quant975, 3), ")"
  )) %>% 
    select(pred_names, Adult) 

display_names_vec <- c(
  "Female",
  "Male", 
  "Age", 
  "No", # Insecticide
  "Yes",
  "No ", # Larvicide
  "Yes ",
  "Number of toilets",
  "Number of water containers",
  "Urban",
  "Rice paddy",
  "Cropland",
  "Distance to river (std.)", 
  "No  ",
  "Yes  ",
  "Flooding index (NFI)",
  "Larval container index",
  "Ave. trapped mosquitos"
) 

pred_names_vec <- c(
  "Female",
  "Male", 
  "Age", 
  "No",
  "Insecticide used",
  "No ",
  "Larvicide used",
  "Number of toilets",
  "Number of water containers",
  "Urban",
  "Rice paddy",
  "Cropland",
  "Distance to river (std.)", 
  "No  ",
  "Wet season",
  "Flooding index (NFI)",
  "Container index",
  "Ave. trapped mosquitos"
  )


all_results <- main_fit_df %>% 
  full_join(larval_fit_df) %>% 
  full_join(adult_fit_df) %>% 
  filter(pred_names != "(Intercept)") %>% 
  add_row(pred_names = "Female", Main = "Reference", Larval = "Reference", Adult = "Reference") %>% 
  add_row(pred_names = "No", Main = "Reference", Larval = "Reference", Adult = "Reference") %>% 
  add_row(pred_names = "No ", Main = "Reference", Larval = "Reference", Adult = "Reference") %>% 
  add_row(pred_names = "No  ", Main = "Reference", Larval = "Reference", Adult = "Reference") %>% 
  add_row(pred_names = "Urban", Main = "Reference", Larval = "Reference", Adult = "Reference") %>% 
  mutate(display_names = factor(
    pred_names, 
    levels = pred_names_vec, 
    labels = display_names_vec 
  )) %>% 
  arrange(display_names) %>% 
  select(pred_names, display_names, Main, Larval, Adult)
```


```{r Table 2 Model estimates}
all_results %>% 
  select(display_names, Main, Larval, Adult) %>% 
kbl(
  #booktabs = TRUE, 
  col.names = c(" ", "Main Model", "Larval Model", "Adult Model")
) %>% 
  kable_styling() %>% 
  add_header_above(
    c(" " = 1, "Mean Estimate (95% BCI)" = 3), 
    line = FALSE,
    align = "c"
  ) %>% 
  pack_rows(
    bold = FALSE,
    index = c(
      "Gender" = 2,
      " " = 1,
      "Insecticide" = 2,
      "Larvicide" = 2,
      " " = 2,
      "Land type" = 3,
      " " = 1,
      "Wet season" = 2,
      " " = 3
    )
  )
```

\newpage

```{r Load in prediction results}
larval_pred_mse_df <- read_csv(here("output", "larval_pred_mse_df.csv"))

adult_pred_mse_df <- read_csv(here("output", "adult_pred_mse_df.csv"))
```


```{r Table 3a Larval and adult predictors}
larval_pred_mse_df %>% 
kbl(booktabs = TRUE) %>% 
  kable_styling()

# "Prediction MSE from cross validation with a 95%-5% split on the larval and adult subsetted data."
```


```{r Table 3b Larval and adult predictors}
adult_pred_mse_df %>% 
kbl(booktabs = TRUE) %>% 
  kable_styling()
```
