---
title: "Aedes serology investigation"
geometry: margin=0.5cm
output: pdf_document
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
params:
  rerun_data: FALSE
  near_river_cut_off: 300
  modis_lag: 32
  rerun_fit_young: FALSE
  rerun_fit_school: FALSE
  fit_main: FALSE
  rerun_fit_v1_surf: FALSE
  rerun_fit_v2_surf: FALSE
  rerun_fit_v3_surf: FALSE
  rerun_fit_v4_surf: FALSE
  rerun_fit_v5_surf: FALSE
  rerun_time_surf: FALSE
  rerun_simple_surf: FALSE
  rerun_wet_surf: FALSE
  rerun_model_surf: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center",
  fig.pos = "h"
)
```


```{r libraries}
library(here)
library(readxl)
library(janitor)
library(viridis)
library(zoo)
library(qwraps2)
library(knitr)
library(kableExtra)
library(lubridate)
library(RANN)
library(rstanarm)
library(bayesplot)
library(gridExtra)
library(grid)
library(lme4)
library(raster)
library(geostatsp)
library(tidyverse)
library(viridis)


source(here("analysis", "process-modis-data-function.R"))

seed_val <- 1423
set.seed(seed_val)
```


```{r read-process-data}
if (params$rerun_data) {
  ##### read-process-survey-data
  
  saliva_ELISA_log_shift <- 0.15
  
  sched_visit_names <- c(
    "VISIT 1 DENGUE INDEX",
    "VISIT 2  DENGUE INDEX",
    "VISIT 3 DENGUE INDEX",
    "VISIT 4 INDEX"
  )
  
  low_count_schools <- c( # schools with <= 5 study participants with saliva measurement
    "Amnor Antarak Cheat School",
    "Ampe Phnom",
    "Aphivodth", 
    "Christian School Khum Skus",
    "Kdey Amnor", 
    "Kindergarten Asian",
    "Kindergarten Kampuchea Asian",
    "Kindergarten Wattbor",
    "Kindergarten​ Salon",
    "Meatophoum School",
    "No Name",
    "Panha Bot School",
    "Phoumi Thmei",
    "Sinsisamuth"
  ) 
  
  
  aedes_survey_og <- read_excel(here("data", "pagodas_combined_data3.xlsx"))
  
  
  aedes_survey_cleaned <- aedes_survey_og %>% 
    clean_names() %>% 
    mutate(wet_season = ifelse(
      visit %in% c("VISIT 1 DENGUE INDEX", "VISIT 3 DENGUE INDEX"),
      yes = "yes",
      no = "no"
    )) %>% 
    mutate(visit_year = case_when(
      visit == "VISIT 1 DENGUE INDEX" ~ 0,
      visit %in% c("VISIT 2  DENGUE INDEX", "VISIT 3 DENGUE INDEX") ~ 1,
      visit == "VISIT 4 INDEX" ~ 2,
      TRUE ~ -99
    )) %>% 
    mutate(age = as.numeric(age)) %>% 
    mutate(age_cented3 = age - 3) %>%
    mutate(age_cented7 = age - 7) %>%
    mutate(age_cented = age - 6) %>%
    mutate(gender = factor(gender)) %>% 
    mutate(school_attended = str_to_title(school_attended)) %>% 
    mutate(specify_if_other = str_to_title(specify_if_other)) %>% 
    mutate(school_attended_all = ifelse(
      school_attended == "Other, Specify:",
      yes = specify_if_other,
      no = school_attended
    )) %>% 
    mutate(school_attended_all = factor(
      case_when(
        school_attended_all == "New Town" ~ "Kindergarten New Town",
        school_attended_all %in% c("Sin Si Sa Muth", "Sinsisamuth") ~ "Kindergarten Sin Si Sa Muth",
        school_attended_all == "Panha Bot" ~ "Panha Bot School",
        school_attended_all == "No Name" ~ "NA",
        TRUE ~ school_attended_all
      ))) %>% 
    mutate(school_attended_all = as.character(school_attended_all)) %>%
    mutate(in_school = factor(ifelse(
      school_attended_all != "Subject Not In School",
      yes = "yes",
      no = "no"
    ))) %>% 
    mutate(school_attended_red = factor(
      case_when(
        school_attended_all %in% low_count_schools ~ "other",
        TRUE ~ school_attended_all
      ),
      levels = c(
        "Subject Not In School",
        "Ang Seri",              
        "Anouvotta",             
        "Mroum Cheung",          
        "Mroum Tbaung",          
        "New Town",
        "Rkathom",
        "Santiphap",
        "Kindergarten Sin Si Sa Muth",
        "other"
      )
    )) %>% 
    select(-c("specify_if_other")) %>% 
    mutate(housing_type = factor(housing_type)) %>% 
    mutate(socioeconomic_class = factor(
      socioeconomic_class,
      levels = c("Very Poor", "Lower", "Middle", "Upper")
    )) %>% 
    mutate(visit_date = as.Date(visit_date)) %>% 
    mutate(sched_visit = ifelse(visit %in% sched_visit_names, yes = "yes", no = "no")) %>% 
    mutate(num_domestic_water_containers_in_home = as.numeric(num_domestic_water_containers_in_home)) %>% 
    mutate(num_toilets_in_home = as.numeric(num_toilets_in_home)) %>% 
    mutate(how_often_use_bed_net = factor(
      how_often_use_bed_net,
      levels = c(
        "Never", 
        "Rarely", 
        "Regularly/ Most of the time", 
        "All of the time"
      ),
      labels = c(
        "Never", 
        "Rarely", 
        "Most of the time", 
        "All of the time"
      )
    )) %>% 
    mutate(insecticide_spray = factor(insecticide_spray)) %>% 
    mutate(larvicide_applied_to_water = factor(larvicide_applied_to_water)) %>% 
    mutate(how_often_mosquito_coils_burned = factor(
      how_often_mosquito_coils_burned,
      levels = c(
        "Never", 
        "Rarely (about 1x/month)", 
        "Sometimes (about 1x/week)",
        "Often (about 3x/week)",
        "Daily"
      ),
      labels = c(
        "Never", 
        "~ 1x/month", 
        "~ 1x/week",
        "~ 3x/week",
        "Daily"
      )
    )) %>% 
    mutate(visit_date_abr = factor(as.yearmon(visit_date))) %>% 
    mutate(log_saliva_elisa = log(saliva_elisa_value + saliva_ELISA_log_shift)) 
  
  
  aedes_visit5 <- read_csv(here("data", "Saliva ELISA V1-6 INDEX.csv"), show_col_types = FALSE) %>% 
    select(study_id = ID, saliva_elisa_value = "Visit 5") %>% 
    mutate(saliva_elisa_value = as.numeric(ifelse(saliva_elisa_value == ".", yes = NA, no = saliva_elisa_value))) %>% 
    mutate(log_saliva_elisa = log(saliva_elisa_value + saliva_ELISA_log_shift)) 
    

  aedes_survey_cleaned_v1_v5 <- aedes_survey_cleaned[!duplicated(aedes_survey_cleaned$study_id), ] %>% 
      mutate(visit = "Visit 5") %>% 
      mutate(visit_date = as.Date("2020-07-01")) %>% 
      mutate(visit_date_abr = NA) %>% 
      mutate(wet_season = "yes") %>% 
      mutate(visit_year = 2) %>% 
      select(-c(saliva_elisa_value, log_saliva_elisa)) %>% 
      full_join(aedes_visit5) %>% 
      select(colnames(aedes_survey_cleaned)) %>% 
      bind_rows(aedes_survey_cleaned) %>% 
      arrange(study_id, visit_date)
  
  
  aedes_coord_og <- read_csv(here("data", "PAGODAS_Coordinates.csv"), show_col_types = FALSE)
  
  aedes_coord_cleaned <- aedes_coord_og %>%
    clean_names()
  
  aedes_full <- full_join(aedes_survey_cleaned_v1_v5, aedes_coord_cleaned) %>% 
    filter(sched_visit == "yes") %>% 
    mutate(visit = case_when(
      visit == "VISIT 1 DENGUE INDEX" ~ "visit1",
      visit == "VISIT 2  DENGUE INDEX" ~ "visit2",
      visit == "VISIT 3 DENGUE INDEX" ~ "visit3",
      visit == "VISIT 4 INDEX" ~ "visit4",
      visit == "Visit 5" ~ "visit5",
      TRUE ~ "NA"
    ))

  aedes_survey_with_river <- read_csv(here("data", "DistPHHtoRiver.csv"), show_col_types = FALSE) %>% 
    select(study_id = Study.ID, distance_to_river = distance) %>%
    mutate(distance_to_river_scaled = (distance_to_river - mean(distance_to_river)) / sd(distance_to_river)) %>% 
    mutate(close_to_river = factor(
      ifelse(distance_to_river <= params$near_river_cut_off, "yes", "no"), 
      levels = c("no", "yes")
    )) %>% 
    right_join(aedes_full)
  
  
  aedes_red <- aedes_survey_with_river %>% 
    filter(!is.na(saliva_elisa_value)) %>% 
    filter(!is.na(visit_date)) %>% 
    filter(school_attended_all != "NA") %>% 
    mutate(num_domestic_water_containers_in_home = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = num_domestic_water_containers_in_home
    )) %>% 
    mutate(num_toilets_in_home = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = num_toilets_in_home
    )) %>% 
    mutate(how_often_use_bed_net = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = as.character(how_often_use_bed_net)
    )) %>% 
    mutate(insecticide_spray = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = as.character(insecticide_spray)
    )) %>%
    mutate(larvicide_applied_to_water = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = as.character(larvicide_applied_to_water)
    )) %>%
    mutate(how_often_mosquito_coils_burned = ifelse(
      visit != "visit1", 
      yes = NA, 
      no = as.character(how_often_mosquito_coils_burned)
    ))

  
  time_varying <- read_xlsx(here("data", "AllVisitDataWithScheDengueRiskFactors.xlsx")) %>% 
    select(
      study_id = "Study ID", 
      visit = "Event Name",
      num_domestic_water_containers_in_home = "1. How many domestic water containers are in the subject's home?",
      num_toilets_in_home = "2. How many toilets are in the subject's home?",
      how_often_use_bed_net = "3. How often does the subject use a bed net?",
      insecticide_spray = "4. Is the subject's home sprayed with insecticide?",
      larvicide_applied_to_water = "5. Is larvicide applied to water containers at the subject's home?",
      how_often_mosquito_coils_burned = "6. How often are mosquito coils burned in the subject's house?",
    ) %>% 
    mutate(visit = gsub(" ", "", str_to_lower(visit), fixed = TRUE)) %>%
    filter(visit != "visit6") %>% 
    filter(!(study_id == "100-0468" & visit == "visit4")) %>% # Missing data
    mutate(num_domestic_water_containers_in_home = as.numeric(num_domestic_water_containers_in_home)) %>% 
    mutate(num_toilets_in_home = as.numeric(num_toilets_in_home)) %>% 
    mutate(how_often_use_bed_net = as.character(factor(
      how_often_use_bed_net,
      levels = c(
        "Never", 
        "Rarely", 
        "Regularly/ Most of the time", 
        "All the time"
      ),
      labels = c(
        "Never", 
        "Rarely", 
        "Most of the time", 
        "All of the time"
      )
    ))) %>% 
    mutate(how_often_mosquito_coils_burned = as.character(factor(
      how_often_mosquito_coils_burned,
      levels = c(
        "Never", 
        "Rarely (about 1x/month)", 
        "Sometimes (about 1x/week)",
        "Often (about 3x/week)",
        "Daily"
      ),
      labels = c(
        "Never", 
        "~ 1x/month", 
        "~ 1x/week",
        "~ 3x/week",
        "Daily"
      )
    )))
  
  time_varying_vars <- c("num_domestic_water_containers_in_home", "num_toilets_in_home", "how_often_use_bed_net", "insecticide_spray", "larvicide_applied_to_water", "how_often_mosquito_coils_burned")
  
  
  aedes_red <- aedes_red %>% 
    filter(visit != "visit1") %>% 
    select(-time_varying_vars) %>% 
    left_join(time_varying) %>% 
    select(colnames(aedes_red)) %>% 
    bind_rows(aedes_red %>% filter(visit == "visit1")) %>% 
    mutate(visit = factor(visit)) %>% 
    mutate(visit5 = factor(ifelse(visit != "visit5", "no", "yes"))) %>% 
    mutate(wet_season = factor(wet_season, levels = c("no", "yes"))) %>% 
    filter(!is.na(num_domestic_water_containers_in_home)) %>% 
    mutate(how_often_use_bed_net = factor(
      how_often_use_bed_net,
      levels = c(
        "Never", 
        "Rarely", 
        "Most of the time", 
        "All of the time"
      )
    )) %>% 
    mutate(insecticide_spray = factor(insecticide_spray)) %>% 
    mutate(larvicide_applied_to_water = factor(larvicide_applied_to_water)) %>% 
    mutate(how_often_mosquito_coils_burned = factor(
      how_often_mosquito_coils_burned,
      levels = c(
        "Never", 
        "~ 1x/month", 
        "~ 1x/week",
        "~ 3x/week",
        "Daily"
      )
    ))
  
  
  aedes_red <- read_csv(here("data", "PAGODAS_Landtype.csv")) %>% 
    select(-c(X, Y, lon, lat, elevation)) %>% 
    clean_names() %>% 
    mutate(modal_land_type = factor(
      str_to_lower(modal_land_type), 
      levels = c("urban", "rice paddy", "cropland")
    )) %>% 
    right_join(aedes_red, by = "study_id")
  
  
  #### Incorporate satellite data
  max_date_diff <- 60
  date_lag <- params$modis_lag
  
  
  sat_data500 <- process_modis_data(
    df_og = read_csv(here("data", "MODIS_500m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 7
  ) %>% 
    arrange(Study.ID, var_type, date)
  
  
  sat_df <- sat_data500
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    df_id <- sat_df %>% 
      filter(Study.ID == as.character(df_og[i, "study_id"]))
    
    for(j in 1:num_vars) {
      df_id_var <- df_id %>% 
        filter(var_type == var_types[j])
      
      if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
        date_diff <- (df_og$visit_date[i] - days(date_lag)) - df_id_var$date
        curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
        
        if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
          print(paste0(
            "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
            var_types[j], " value available within ", max_date_diff, 
            " days [max_date_diff] of ", date_lag, " days [date_lag] prior to visit date!"
          ))
        } else {
          df_new[i, var_types[j]] <- curr$sat_var_value
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI500_home = EVI, NVI500_home = NVI, NFI500_home = NFI)
  
  
  #### Incorporate satellite data 
  sat_data250 <- process_modis_data(
    df_og = read_csv(here("data", "MODIS_250m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 7
  )
  
  
  sat_df <- sat_data250
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    df_id <- sat_df %>% 
      filter(Study.ID == as.character(df_og[i, "study_id"]))
    
    for(j in 1:num_vars) {
      df_id_var <- df_id %>% 
        filter(var_type == var_types[j])
      
      if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
        date_diff <- (df_og$visit_date[i] - days(date_lag)) - df_id_var$date
        curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
        
        if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
          print(paste0(
            "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
            var_types[j], " value available within ", max_date_diff, 
            " days [max_date_diff] of ", date_lag, " days [date_lag] prior to visit date!"
          ))
        } else {
          df_new[i, var_types[j]] <- curr$sat_var_value
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI250_home = EVI, NVI250_home = NVI, NFI250_home = NFI)
  
  
    #### Incorporate satellite data 16 days
  sat_data250 <- process_modis_data(
    df_og = read_csv(here("data", "MODIS_250m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 7
  )
  
  
  sat_df <- sat_data250
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    df_id <- sat_df %>% 
      filter(Study.ID == as.character(df_og[i, "study_id"]))
    
    for(j in 1:num_vars) {
      df_id_var <- df_id %>% 
        filter(var_type == var_types[j])
      
      if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
        date_diff <- (df_og$visit_date[i] - days(16)) - df_id_var$date
        curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
        
        if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
          print(paste0(
            "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
            var_types[j], " value available within ", max_date_diff, 
            " days [max_date_diff] of ", 16, " days [16] prior to visit date!"
          ))
        } else {
          df_new[i, var_types[j]] <- curr$sat_var_value
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI250_home16 = EVI, NVI250_home16 = NVI, NFI250_home16 = NFI)
  
  
      #### Incorporate satellite data 48 days
  sat_data250 <- process_modis_data(
    df_og = read_csv(here("data", "MODIS_250m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 7
  )
  
  
  sat_df <- sat_data250
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    df_id <- sat_df %>% 
      filter(Study.ID == as.character(df_og[i, "study_id"]))
    
    for(j in 1:num_vars) {
      df_id_var <- df_id %>% 
        filter(var_type == var_types[j])
      
      if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
        date_diff <- (df_og$visit_date[i] - days(48)) - df_id_var$date
        curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
        
        if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
          print(paste0(
            "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
            var_types[j], " value available within ", max_date_diff, 
            " days [max_date_diff] of ", 48, " days [48] prior to visit date!"
          ))
        } else {
          df_new[i, var_types[j]] <- curr$sat_var_value
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI250_home48 = EVI, NVI250_home48 = NVI, NFI250_home48 = NFI)
  
  
  #### Incorporate school satellite data 
  sat_data250 <- process_modis_data(
    df_og = read_csv(here("data", "SchoolsMODIS_250m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 6
  ) %>% 
    mutate(names = ifelse(
      names == "Kindergarten<U+200B> Salon", 
      yes = "Kindergarten​ Salon", 
      no = names
    ))
  
  
  sat_df <- sat_data250
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    if(df_og[i, "school_attended_all"] != "Subject Not In School") {
      df_id <- sat_df %>% 
        filter(names == as.character(df_og[i, "school_attended_all"]))
      
      for(j in 1:num_vars) {
        df_id_var <- df_id %>% 
          filter(var_type == var_types[j])
        
        if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
          date_diff <- (df_og$visit_date[i] - days(date_lag)) - df_id_var$date
          curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
          
          if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
            print(paste0(
              "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
              var_types[j], " value available within ", max_date_diff, 
              " days [max_date_diff] of ", date_lag, " days [date_lag] prior to visit date!"
            ))
          } else {
            df_new[i, var_types[j]] <- curr$sat_var_value
          }
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI250_sch = EVI, NVI250_sch = NVI, NFI250_sch = NFI) %>% 
    mutate(EVI250_sch = ifelse(is.na(EVI250_sch), yes = 0, no = EVI250_sch)) %>% 
    mutate(NVI250_sch = ifelse(is.na(NVI250_sch), yes = 0, no = NVI250_sch)) %>% 
    mutate(NFI250_sch = ifelse(is.na(NFI250_sch), yes = 0, no = NFI250_sch))                 
  
  aedes_red <- aedes_red[!is.na(aedes_red$NVI250_home), ]
  
  
   #### Incorporate school satellite data 16
  sat_data250 <- process_modis_data(
    df_og = read_csv(here("data", "SchoolsMODIS_250m.csv"), show_col_types = FALSE), 
    sat_var_names = c("EVI", "NVI", "NFI"), # keep order that it appear in df
    sat_var_col_start = 6
  ) %>% 
    mutate(names = ifelse(
      names == "Kindergarten<U+200B> Salon", 
      yes = "Kindergarten​ Salon", 
      no = names
    ))
  
  
  sat_df <- sat_data250
  df_og <- aedes_red
  df_new <- cbind(
    df_og, 
    "EVI" = rep(NA, nrow(df_og)),
    "NFI" = rep(NA, nrow(df_og)),
    "NVI" = rep(NA, nrow(df_og))
  )
  
  num_vars <- 3
  var_types <- levels(factor(sat_df$var_type))
  
  
  for(i in 1:nrow(df_og)) {
    if(df_og[i, "school_attended_all"] != "Subject Not In School") {
      df_id <- sat_df %>% 
        filter(names == as.character(df_og[i, "school_attended_all"]))
      
      for(j in 1:num_vars) {
        df_id_var <- df_id %>% 
          filter(var_type == var_types[j])
        
        if (sum(!is.na(df_id_var$sat_var_value)) > 0) {
          date_diff <- (df_og$visit_date[i] - days(16)) - df_id_var$date
          curr <- df_id_var[which.min(ifelse(date_diff < 0, 1000, date_diff)), ]
          
          if (abs(curr$date - df_og$visit_date[i]) > max_date_diff) {
            print(paste0(
              "Warning: Study ID ", df_og[i, "study_id"], " does not have ", 
              var_types[j], " value available within ", max_date_diff, 
              " days [max_date_diff] of ", 16, " days [16] prior to visit date!"
            ))
          } else {
            df_new[i, var_types[j]] <- curr$sat_var_value
          }
        }
      }
    }
  }
  
  aedes_red <- df_new %>% 
    rename(EVI250_sch16 = EVI, NVI250_sch16 = NVI, NFI250_sch16 = NFI) %>% 
    mutate(EVI250_sch16 = ifelse(is.na(EVI250_sch16), yes = 0, no = EVI250_sch16)) %>% 
    mutate(NVI250_sch16 = ifelse(is.na(NVI250_sch16), yes = 0, no = NVI250_sch16)) %>% 
    mutate(NFI250_sch16 = ifelse(is.na(NFI250_sch16), yes = 0, no = NFI250_sch16))                 
  
  
  #### Incorporate larval data
  larval_lat_lo <- read_csv(here("data", "HH_Surveys_19Jan_UTM48N.csv"), show_col_types = FALSE) %>% 
    select(
      X = "X...1",
      Y = "Y...2",
      larval_lon = "X...3",
      larval_lat = "Y...4",
      house_num = "name",
      subj_id = "SUBJID"
    ) %>% 
    mutate(subj_id = as.character(as.numeric(subj_id))) %>% 
    filter(!duplicated(subj_id)) #subjects 389 and 716 had repeat measurements; 1st kept
    
  
  larval_hs <- read_xlsx(here("data", "House Survey Data_Extracted 03May2021.xlsx")) %>% 
    select(
      subj_id = SUBJID,
      larval_visit_date = VISITDAT,
      water_containers = WATERCON,
      water_larvae = WATERLARVAE
    ) %>% 
    filter(water_containers > 0) %>% 
    mutate(subj_id = as.character(subj_id)) %>% 
    mutate(container_index = as.numeric(water_larvae) / as.numeric(water_containers)) %>% 
    left_join(y = larval_lat_lo) 
  
  larval_nn <- nn2(
    select(.data = larval_hs, larval_lon, larval_lat),
    query = select(.data = aedes_red, lon, lat), 
    k = 1,
    radius = 300
  )
  
  aedes_red <- aedes_red %>% 
    mutate(larvae_cont_ind = larval_hs$container_index[larval_nn$nn.idx]) %>% 
    mutate(lat_s = (lat - mean(lat)) / sd(lat)) %>% 
    mutate(lon_s = (lon - mean(lon)) / sd(lon)) %>% 
    mutate(time = as.numeric(case_when(
      visit == "visit1" ~ 1,
      visit == "visit2" ~ 2,
      visit == "visit3" ~ 3,
      visit == "visit4" ~ 4,
      visit == "visit5" ~ 5
    )))
  
  
  saveRDS(aedes_red, file = here("data", "processed_aedes_data.rds"))
  
} else { 
  aedes_red <- readRDS(file = here("data", "processed_aedes_data.rds")) 
}
  

aedes_red_ind <- aedes_red %>%
  filter(visit == "visit1") %>% 
  mutate(visit = droplevels(visit))
```


## Exposure surfaces by visit

```{r, fig.asp=1}
aedes_red_ind %>% 
  ggplot(mapping = aes(x = lon, y = lat)) +
  geom_point() +
  theme_bw() +
  coord_equal(ratio = 1) +
  lims(x = c(104.50, 104.56), y = c(11.43, 11.49))
```


```{r visit1-exposure-surface}
if(params$rerun_fit_v1_surf){
  aedes_v1 <- filter(aedes_red, visit == "visit1")
  
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_v1, x = lon, y = lat),
    data = select(aedes_v1, log_saliva_elisa)
  )
  
  fit_v1_surf <- glgm(
    formula = log_saliva_elisa ~ 1,
    data = spdf,
    grid = 75
  )
  
  saveRDS(fit_v1_surf, here("output/map-models", "fit_v1_surf.rds"))
} else {
  fit_v1_surf <- readRDS(here("output/map-models", "fit_v1_surf.rds"))
}
```

```{r visit2-exposure-surface}
if(params$rerun_fit_v2_surf){
  aedes_v2 <- filter(aedes_red, visit == "visit2")
  
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_v2, x = lon, y = lat),
    data = select(aedes_v2, log_saliva_elisa)
  )
  
  fit_v2_surf <- glgm(
    formula = log_saliva_elisa ~ 1,
    data = spdf,
    grid = 75,
  )
  
  saveRDS(fit_v2_surf, here("output/map-models", "fit_v2_surf.rds"))
} else {
  fit_v2_surf <- readRDS(here("output/map-models", "fit_v2_surf.rds"))
}
```

```{r visit3-exposure-surface}
if(params$rerun_fit_v3_surf){
  aedes_v3 <- filter(aedes_red, visit == "visit3")
  
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_v3, x = lon, y = lat),
    data = select(aedes_v3, log_saliva_elisa)
  )
  
  fit_v3_surf <- glgm(
    formula = log_saliva_elisa ~ 1,
    data = spdf,
    grid = 75
  )
  
  saveRDS(fit_v3_surf, here("output/map-models", "fit_v3_surf.rds"))
} else {
  fit_v3_surf <- readRDS(here("output/map-models", "fit_v3_surf.rds"))
}
```

```{r visit4-exposure-surface}
if(params$rerun_fit_v4_surf){
  aedes_v4 <- filter(aedes_red, visit == "visit4")
  
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_v4, x = lon, y = lat),
    data = select(aedes_v4, log_saliva_elisa)
  )
  
  fit_v4_surf <- glgm(
    formula = log_saliva_elisa ~ 1,
    data = spdf,
    grid = 75
  )
  
  saveRDS(fit_v4_surf, here("output/map-models", "fit_v4_surf.rds"))
} else {
  fit_v4_surf <- readRDS(here("output/map-models", "fit_v4_surf.rds"))
}
```

```{r display-visit-exposure-surface1-4, fig.width=7.5, fig.asp=1, fig.align="center"}
fit_visit_surfs <- bind_rows(
  as.data.frame(fit_v1_surf$raster$predict.mean, xy = TRUE) %>% 
  mutate(visit = "Visit 1"),
  as.data.frame(fit_v2_surf$raster$predict.mean, xy = TRUE) %>% 
  mutate(visit = "Visit 2"),
  as.data.frame(fit_v3_surf$raster$predict.mean, xy = TRUE) %>% 
  mutate(visit = "Visit 3"),
  as.data.frame(fit_v4_surf$raster$predict.mean, xy = TRUE) %>% 
  mutate(visit = "Visit 4")
)


ggplot() +
  geom_raster(
    data = fit_visit_surfs, 
    aes(x = x, y = y, fill = predict.mean)
  ) +
  coord_quickmap() +
  scale_fill_viridis(direction = -1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggtitle("Aedes Exposure Surface") +
  coord_equal(ratio = 1) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.background = element_blank()) +
  facet_wrap( ~ visit, ncol = 2)
```

```{r visit5-exposure-surface}
if(params$rerun_fit_v5_surf){
  aedes_v5 <- filter(aedes_red, visit == "visit5")
  
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_v5, x = lon, y = lat),
    data = select(aedes_v5, log_saliva_elisa)
  )
  
  fit_v5_surf <- glgm(
    formula = log_saliva_elisa ~ 1,
    data = spdf,
    grid = 75
  )
  
  saveRDS(fit_v5_surf, here("output/map-models", "fit_v5_surf.rds"))
} else {
  fit_v5_surf <- readRDS(here("output/map-models", "fit_v5_surf.rds"))
}

v5_surf_df <- as.data.frame(fit_v5_surf$raster$predict.mean, xy = TRUE)

ggplot() +
  geom_raster(
    data = v5_surf_df, 
    aes(x = x, y = y, fill = predict.mean)
  ) +
  coord_quickmap() +
  scale_fill_viridis(direction = -1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggtitle("Aedes Exposure Surface") +
  coord_equal(ratio = 1) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.background = element_blank())
```


## Intermediate models
```{r time-exposure-surface}
if(params$rerun_time_surf){
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_red, x = lon, y = lat),
    data = select(aedes_red, log_saliva_elisa, visit)
  )
  
  time_surf <- glgm(
    formula = log_saliva_elisa ~ visit,
    data = spdf,
    grid = 75
  )
  
  saveRDS(time_surf, here("output/map-models", "time_surf.rds"))
} else {
  time_surf <- readRDS(here("output/map-models", "time_surf.rds"))
}

plot(time_surf$raster$predict.mean, main = "Time model Aedes Exposure Surface",asp=1)

time_surf$parameters$summary %>% select(mean, "0.025quant", "0.975quant") %>% round(3)
```

```{r simple-exposure-surface}
if(params$rerun_simple_surf){
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_red, x = lon, y = lat),
    data = select(aedes_red, log_saliva_elisa, wet_season, visit5)
  )
  
  simple_surf <- glgm(
    formula = log_saliva_elisa ~ wet_season + visit5,
    data = spdf,
    grid = 75
  )
  
  saveRDS(simple_surf, here("output/map-models", "simple_surf.rds"))
} else {
  simple_surf <- readRDS(here("output/map-models", "simple_surf.rds"))
}

plot(simple_surf$raster$predict.mean, main = "Simple model Aedes Exposure Surface",asp=1)

simple_surf$parameters$summary %>% select(mean, "0.025quant", "0.975quant") %>% round(3)
```

```{r wetseason-exposure-surface}
aedes_red1 <- filter(aedes_red, wet_season == "yes") 

if(params$rerun_wet_surf){
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_red1, x = lon, y = lat),
    data = select(aedes_red1, log_saliva_elisa, visit5)
  )
  
  wet_season_surf <- glgm(
    formula = log_saliva_elisa ~ visit5,
    data = spdf,
    grid = 75
  )
  
  saveRDS(wet_season_surf, here("output/map-models", "wet_season_surf.rds"))
} else {
  wet_season_surf <- readRDS(here("output/map-models", "wet_season_surf.rds"))
}

plot(wet_season_surf$raster$predict.mean, main = "Wet season Aedes Exposure Surface",asp=1)

wet_season_surf$parameters$summary %>% select(mean, "0.025quant", "0.975quant") %>% round(3)
```

## Main model
```{r model-exposure-surface}
if(params$rerun_model_surf){
  spdf <- SpatialPointsDataFrame(
    coords = select(aedes_red, x = lon, y = lat),
    data = select(aedes_red, log_saliva_elisa, 
      gender, 
      age_cented7, distance_to_river_scaled,
      modal_land_type,
      num_toilets_in_home, num_domestic_water_containers_in_home,
      insecticide_spray, larvicide_applied_to_water,
      NFI250_home, EVI250_home,
      wet_season, visit_year,
      visit5
    ))
  
  fit_model_surf <- glgm(
    formula = log_saliva_elisa ~ gender + 
      age_cented7  + distance_to_river_scaled +
      modal_land_type +
      num_toilets_in_home + num_domestic_water_containers_in_home +
      insecticide_spray + larvicide_applied_to_water  +
      NFI250_home  +
      wet_season + visit_year +
      visit5,
    data = spdf,
    grid = 75
  )
  
  saveRDS(fit_model_surf, here("output/map-models", "fit_model_surf.rds"))
} else {
  fit_model_surf <- readRDS(here("output/map-models", "fit_model_surf.rds"))
}

plot(fit_model_surf$raster$predict.mean, main = "Model Aedes Exposure Surface",asp=1)

plot(fit_model_surf$raster$predict.0.025quant, main = "Model Aedes Exposure Surface",asp=1)

plot(fit_model_surf$raster$predict.0.975quant, main = "Model Aedes Exposure Surface",asp=1)

plot(fit_model_surf$raster$predict.sd, main = "Model Aedes Exposure Surface",asp=1)

fit_model_surf$parameters$summary %>% select(mean, "0.025quant", "0.975quant") %>% round(3)
```



