---
title: "Fingerprick time series with lowess smooth"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.pos = 'H', fig.align = "center",
  message = FALSE, warning = FALSE
)
```


```{r Load libraries}
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(viridis)
library(gridExtra)
```


```{r Load data}
f_dates_og <- read_excel(
  here("data", "Finger Prick dataset_Dates.xlsx"),
  na = c("NA", "Confuse")
)

f_dates <- f_dates_og %>% 
  pivot_longer(
    cols = paste0("Date_E_M", 1:12), 
    names_to = "month",
    names_prefix = "Date_E_M", 
    values_to = "visit_date"
  ) %>% 
  mutate(visit_date = as.Date(visit_date)) %>% 
  rename(id = `Sample ID`)

fld_og <- read_csv(
  here("data", "Fingerprick Location Data.csv"),
  na = c("", "NA", "."),
  show_col_types = FALSE
)

f_data <- fld_og %>% 
  pivot_longer(
    cols = paste0("Aedes_SGH_ELISA_M", 1:12), 
    names_to = "month", 
    names_prefix = "Aedes_SGH_ELISA_M",
    values_to = "ELISA"
  ) %>% 
  rename(id = `Sample ID`, school = `School attended`, lon = Lat, lat = Lon) %>% # Lat and Lon are switched!! 
  mutate(log_elisa = log(ELISA + 0.0001)) %>% 
  mutate(Village = factor(Village)) %>% 
  left_join(f_dates, by = c("id", "month")) %>% 
  filter(!is.na(Village)) %>% 
  filter(!is.na(ELISA)) %>% 
  filter(!is.na(visit_date))
```


```{r Produce lowess plot}
ggplot(f_data, aes(x = visit_date, y = ELISA)) +
  geom_point() + 
  facet_wrap(~ Village, nrow = 1) +
  geom_smooth(method = "loess") +
  theme_bw() +
  ylab("ELISA") +
  xlab("Date")

smooth_plot <- ggplot(f_data, aes(x = visit_date, y = log_elisa)) +
  geom_point() + 
  facet_wrap(~ Village, nrow = 1) +
  geom_smooth(method = "loess") +
  theme_bw() +
  ylab("log(ELISA)") +
  xlab("Sample collection date") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r Load visit prediction surface data}
aedes_red <- readRDS(file = here("data", "processed_aedes_data.rds"))
  
ind_visit_surf_df <- readRDS(here("output", "ind_visit_surf_df.rds"))

```

``` {r Plot visit prediction surface}
fit_y <- lm(y_m ~ lat, data = ind_visit_surf_df)

y_coef <- as.vector(fit_y$coefficients)

lat_labels <- c(11.45, 11.46, 11.47)

lat_breaks <- y_coef[1] + y_coef[2] * lat_labels

fit_x <- lm(x_m ~ lon, data = ind_visit_surf_df)

x_coef <- as.vector(fit_x$coefficients)

lon_labels <- c(104.51, 104.53, 104.55)

lon_breaks <- x_coef[1] + x_coef[2] * lon_labels


f_data <- f_data %>% 
  mutate(x_m = x_coef[1] + x_coef[2] * lon) %>% 
  mutate(y_m = y_coef[1] + y_coef[2] * lat)

surface_plot <- ind_visit_surf_df %>% 
  mutate("Predicted Exposure" = Prediction) %>% 
  filter(type == "Mean") %>% 
  filter(visit == "Visit 4") %>% 
  filter(x_m >= x_coef[1] + x_coef[2] * 104.50 & x_m <= x_coef[1] + x_coef[2] * 104.56) %>% 
  filter(y_m >= y_coef[1] + y_coef[2] * 11.44 & y_m <= y_coef[1] + y_coef[2] * 11.48) %>% 
ggplot() +
  geom_raster(mapping = aes(x = x_m, y = y_m, fill = `Predicted Exposure`)) +
  coord_equal() +
  scale_fill_viridis() +
  xlab("Longitude") +
  ylab("Latitude") +
  theme_bw() +
  theme(
    strip.background = element_rect(fill = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "white"),
    panel.background = element_rect(fill = NA),
    panel.ontop = TRUE,
    panel.border = element_blank(),
    legend.position = "left",
    legend.direction = "vertical",
    legend.box = "horizontal"
  ) +
  scale_y_continuous(breaks = lat_breaks, labels = lat_labels) +
  scale_x_continuous(breaks = lon_breaks, labels = lon_labels) +
  geom_point(data = f_data, mapping = aes(x = x_m, y = y_m, color = Village))
```


```{r}
grid.arrange(
  smooth_plot, surface_plot, 
  nrow = 2, 
  heights = c(4, 5)
)
```


```{r}
wet_months <- as.character(5:10)

f_data <- f_data %>% 
  mutate(Season = ifelse(
    month(visit_date) %in% wet_months,
    yes = "Wet",
    no = "Dry"
  ))

f_data %>% 
  ggplot(aes(x = Season, y = log_elisa)) +
  geom_boxplot() +
  theme_bw() +
  ylab("Log(ELISA)")

f_data %>% 
  ggplot(aes(x = log_elisa, color = Season, fill = Season)) +
  geom_histogram(alpha = 0.5, position = "identity") +
  theme_bw() +
  xlab("Log(ELISA)")
```

